title: Sensor Technology Adapter Gateway
logo: /assets/img/stag_icon_wblue.png
favicon: /assets/img/favicon.ico
email: stag@hahn-schickard.de
description: >- 
  Sensor Technology Adapter Gateway (STAG) - modular integration software for Industry 4.0
baseurl: "" 
url: "" 

theme: bulma-clean-theme

fixed_navbar: top
footer_menu: footer
contact_us: contact_us
theme_color: '#333333'

defaults:
  -
    scope:
      path: ""
    values:
      hero_height: is-small
      hero_color: linear-gradient(90deg, rgba(51,51,51,1) 0%, rgba(52,52,52,1) 60%, rgba(241,241,241,1) 80%, rgba(255,255,255,1) 100%)
      hero_logo: /assets/img/stag_logo.png
