title: Sensor Technology Adapter Gateway
logo: /assets/img/stag_icon_wblue.png
favicon: /assets/img/favicon.ico
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/software-sollutions/application-engineering/internal/opc_ua_dev_group/gateway-project/homepage" 
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  jekyll

# Build settings
theme: bulma-clean-theme
plugins:
  - jekyll-feed

fixed_navbar: top
footer_menu: footer
contact_us: contact_us
theme_color: '#333333'

markdown: kramdown
highlighter: rouge

defaults:
  -
    scope:
      path: ""
    values:
      hero_height: is-small
      hero_color: linear-gradient(90deg, rgba(51,51,51,1) 0%, rgba(52,52,52,1) 60%, rgba(241,241,241,1) 80%, rgba(255,255,255,1) 100%)
      hero_logo: /assets/img/stag_logo.png
